---
abstract: 'more mixin helpers for RDBO'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Rose-DBx-Object-MoreHelpers
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: '0'
  Math::BigInt: '0'
  Rose::DB::Object: '0.77'
  Rose::DBx::TestDB: '0'
  Scalar::Util: '0'
  Test::More: '0'
  perl: '5.008003'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Rose-DBx-Object-MoreHelpers
  homepage: https://github.com/karpet/rose-dbx-object-morehelpers
  license: http://dev.perl.org/licenses/
  repository: https://github.com/karpet/rose-dbx-object-morehelpers
version: '0.100'
