--- #YAML:1.0
name:                Rose-DBx-Object-MoreHelpers
version:             0.03
abstract:            more mixin helpers for RDBO
license:             ~
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Data::Dump:                    0
    Rose::DB::Object:              0.77
    Scalar::Util:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
