--- #YAML:1.0
name:               Rose-DBx-Object-MoreHelpers
version:            0.08
abstract:           more mixin helpers for RDBO
author:
    - Peter Karman <karman@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:         0
    Rose::DB::Object:   0.77
    Rose::DBx::TestDB:  0
    Scalar::Util:       0
    Test::More:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
